use_frameworks!

def shared
    pod 'SwiftVIPER', :path => '../'
    pod 'SwiftVIPER/UIKitTable', :path => '../'
end

target 'SwiftVIPERDemo' do
    platform :ios, '8.0'
    shared
end

target 'SwiftVIPER_Tests' do
    platform :ios, '8.0'
    shared
end

target 'Playground' do
    platform :ios, '8.0'
    shared
end
