use_frameworks!
target 'SwiftVIPER_Tests' do
  platform :ios, '8.0'

  pod 'SwiftVIPER', :path => '../'
  pod 'SwiftVIPER/UIKitTable', :path => '../'
end

target 'Playground' do
    platform :ios, '8.0'
    
    pod 'SwiftVIPER', :path => '../'
end
